services:
  db:
    image: postgres:16
    container_name: shaun-the-sheep-ai
    environment:
      POSTGRES_DB: sheep-ai-db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 5656
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: