spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sheep-ai-db
    username: user
    password: 5656
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
  flyway:
    baseline-on-migrate: true
    baseline-version: 1

gemini:
  api:
    url: https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent
    key: ${GEMINI_API_KEY:AIzaSyB_2HpZAgp2_ORDmWZ21TI18sgNQ_DGNDM}

