spring:
  dotenv:
    location: .env.local
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/sheep-ai-db}
    username: ${DB_USERNAME:user}
    password: ${DB_PASSWORD:5656}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true
    baseline-version: 1

gemini:
  api:
    url: https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent
    key: ${GEMINI_API_KEY:AIzaSyB_2HpZAgp2_ORDmWZ21TI18sgNQ_DGNDM}

jwt:
  secret: n3Jka8+vTtK8aJ4zr9H3yX2lV9DGKQ1LNzR7BtYk9fA=
  access-token-expiration: 3600000 # 1?? (ms)
  refresh-token-expiration: 604800000 # 7? (ms)

# RecommendController용 설정
gemini.api.key: ${GEMINI_API_KEY:AIzaSyB_2HpZAgp2_ORDmWZ21TI18sgNQ_DGNDM}
gemini.api.url: https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent