server:
  port: 8080

spring:
  dotenv:
    location: .env.local
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/sheep-ai-db}
    username: ${DB_USERNAME:user}
    password: ${DB_PASSWORD:5656}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 2
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true
    baseline-version: 1
chat:
  md-json:
    storage-dir: ./md-reports
gemini:
  api:
    url: https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent
    key: ${GEMINI_API_KEY}
naver:
  api:
    id: ${NAVER_API_ID}
    secret: ${NAVER_API_SECRET}
jwt:
  secret: ${JWT_SECRET:4a8NRS86guvb1rzq1vlFPXOR4Nx96iKv4lnBAzDx8xo=}
  access-token-expiration: 36000000 # 10 hour (ms)
  refresh-token-expiration: 604800000 # 7 days (ms)
  guest-token-expiration: 1800000  # 30 minutes (ms)

