spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sheep-ai-db
    username: user
    password: 5656
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
  flyway:
    baseline-on-migrate: true
    baseline-version: 1
jwt:
  secret: n3Jka8+vTtK8aJ4zr9H3yX2lV9DGKQ1LNzR7BtYk9fA=
  access-token-expiration: 3600000 # 1?? (ms)
  refresh-token-expiration: 604800000 # 7? (ms)