spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/sheep-ai-db}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true
    baseline-version: 1
  gemini:
    api:
      url: https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent
      key: ${GEMINI_API_KEY}
jwt:
  secret: ${JWT_SECRET_KEY}
  access-token-expiration: 3600000 # 1?? (ms)
  refresh-token-expiration: 604800000 # 7? (ms)